// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function GetAllDownloads():Promise<Array<main.DownloadItem>>;

export function GetCPUUsage():Promise<main.CPUMetrics>;

export function GetDiskUsage():Promise<main.DiskMetrics>;

export function GetDownloadProgress(arg1:string):Promise<main.DownloadItem>;

export function GetMemoryUsage():Promise<main.MemoryMetrics>;

export function GetSettings():Promise<{[key: string]: any}>;

export function GetSystemMetrics():Promise<main.SystemMetrics>;

export function GetWorkspacePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PauseDownload(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetWorkspacePath(arg1:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartDownload(arg1:string,arg2:string):Promise<string>;
