// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUUsage() {
  return window['go']['main']['App']['GetCPUUsage']();
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetMemoryUsage() {
  return window['go']['main']['App']['GetMemoryUsage']();
}

export function GetSystemMetrics() {
  return window['go']['main']['App']['GetSystemMetrics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
