// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCPUUsage():Promise<main.CPUMetrics>;

export function GetDiskUsage():Promise<main.DiskMetrics>;

export function GetMemoryUsage():Promise<main.MemoryMetrics>;

export function GetSystemMetrics():Promise<main.SystemMetrics>;

export function Greet(arg1:string):Promise<string>;
