// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function GetAllDownloads() {
  return window['go']['main']['App']['GetAllDownloads']();
}

export function GetCPUUsage() {
  return window['go']['main']['App']['GetCPUUsage']();
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetDownloadProgress(arg1) {
  return window['go']['main']['App']['GetDownloadProgress'](arg1);
}

export function GetMemoryUsage() {
  return window['go']['main']['App']['GetMemoryUsage']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemMetrics() {
  return window['go']['main']['App']['GetSystemMetrics']();
}

export function GetWorkspacePath() {
  return window['go']['main']['App']['GetWorkspacePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetWorkspacePath(arg1) {
  return window['go']['main']['App']['SetWorkspacePath'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}
